server:
  port: ":8080"
  timeout: 10s

eth:
  nodeURL: "http://localhost:8545"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
  expire: 5m

mysql:
  dsn: "root:123456@tcp(127.0.0.1:3306)/blockchain_asset?charset=utf8mb4&parseTime=True&loc=Local"
